package com.kerosene.kfe.model;

public enum KfeNotificationEventType {
    // Deposits
    DEPOSIT_DETECTED,
    DEPOSIT_CONFIRMATION_PROGRESS,
    DEPOSIT_CONFIRMED,
    DEPOSIT_FINALIZED,
    DEPOSIT_DROPPED,
    DEPOSIT_CONFLICTED,
    DEPOSIT_REVERSED,
    DEPOSIT_RECONCILED,
    DEPOSIT_UNDERPAID,

    // Payments
    PAYMENT_PROCESSING,
    PAYMENT_BROADCAST,
    PAYMENT_IN_FLIGHT,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_CONFLICTED,
    PAYMENT_REPLACED,
    PAYMENT_RECONCILIATION_REQUIRED,

    // Reserves
    RESERVE_CREATED,
    RESERVE_RELEASED
}
